apiVersion: v2
name: gigapipe-stack
description: Complete monitoring stack with Gigapipe & Clickhouse

type: application

version: 0.1.0
maintainers:
- name: lur1an
  email: lurian-code@protonmail.com
  url: https://github.com/lur1an

appVersion: "v4.0.15-alpha"

dependencies:
- name: altinity-clickhouse-operator
  version: 0.25.0
  repository: https://docs.altinity.com/clickhouse-operator/
- name: grafana
  version: 8.6.2
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
