apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: gigapipe
spec:
  defaults:
    templates:
      podTemplate: default
      dataVolumeClaimTemplate: default
      logVolumeClaimTemplate: default
      serviceTemplate: default
  configuration:
    {{- if or (gt (int .Values.clickhouse.shards) 1) (gt (int .Values.clickhouse.replicas) 1) }}
    zookeeper:
      nodes:
        {{- $keeperReplicas := .Values.clickhouse.keeper.replicas | default 3 }}
        {{- range $i := until (int $keeperReplicas) }}
        - host: chk-gigapipe-keeper-0-{{ $i }}
          port: 2181
        {{- end }}
    {{- end }}
    users:
      gigapipe/password: gigapipe
      gigapipe/networks/ip: 
      - 0.0.0.0
      gigapipe/networks/host_regexp: .*
    clusters:
      - name: gigapipe
        layout:
          shardsCount: {{ .Values.clickhouse.shards }}
          replicasCount: {{ .Values.clickhouse.replicas }}
  templates:
    podTemplates:
      - name: default
        spec:
          {{- with .Values.clickhouse.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:25.6
              ports:
                - name: http
                  containerPort: 8123
                - name: tcp
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
    serviceTemplates:
      - name: default
        generateName: "{chi}"
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
            - name: interserver
              port: 9009
    volumeClaimTemplates:
      - name: default
        spec:
          {{- if .Values.clickhouse.storageClass }}
          storageClassName: {{ .Values.clickhouse.storageClass }}
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
      - name: default
        spec:
          {{- if .Values.clickhouse.storageClass }}
          storageClassName: {{ .Values.clickhouse.storageClass }}
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
