{{- if or (gt (int .Values.clickhouse.shards) 1) (gt (int .Values.clickhouse.replicas) 1) }}
apiVersion: clickhouse-keeper.altinity.com/v1
kind: ClickHouseKeeperInstallation
metadata:
  name: gigapipe
spec:
  defaults:
    templates:
      podTemplate: default
      dataVolumeClaimTemplate: default
      serviceTemplate: default
  configuration:
    clusters:
      - name: keeper
        layout:
          replicasCount: {{ .Values.clickhouse.keeper.replicas | default 3 }}
    settings:
      logger/level: information
      logger/console: "true"
      listen_host: 0.0.0.0
      keeper_server/tcp_port: 2181
      keeper_server/four_letter_word_white_list: "*"
      keeper_server/coordination_settings/session_timeout_ms: 30000
      keeper_server/coordination_settings/operation_timeout_ms: 10000
      keeper_server/raft_configuration/raft_logs_level: information
  templates:
    podTemplates:
      - name: default
        spec:
          containers:
            - name: clickhouse-keeper
              image: clickhouse/clickhouse-keeper:latest
              ports:
                - name: client
                  containerPort: 2181
                - name: raft
                  containerPort: 9234
                - name: metrics
                  containerPort: 7000
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "1"
    serviceTemplates:
      - name: default
        generateName: "{chi}"
        spec:
          type: ClusterIP
          ports:
            - name: client
              port: 2181
              targetPort: 2181
            - name: raft
              port: 9234
              targetPort: 9234
            - name: metrics
              port: 7000
              targetPort: 7000
    volumeClaimTemplates:
      - name: default
        spec:
          {{- if .Values.clickhouse.storageClass }}
          storageClassName: {{ .Values.clickhouse.storageClass }}
          {{- end }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
{{- end }}
