apiVersion: v1
kind: Service
metadata:
  name: gigapipe
  labels:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.gigapipe.image.tag | default "latest" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.gigapipe.service.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.gigapipe.service.port | default 3100 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: gigapipe
    app.kubernetes.io/instance: {{ .Release.Name }}
